Repository P3-Hype/SRAMS-frontend, pull requests merged in 2023-10, with the labels that each got.

#22 Feature/11 mui theme
  package-lock.json
  package.json
  src/App.tsx
  src/components/BasePage/BasePage.tsx
  src/components/Header/Header.tsx
  src/hooks/useAlert.tsx
  src/theme.tsx
Labels: enhancement

#25 updated var names + set default view to grid
  src/components/ToggleView/ToggleView.tsx
Labels: enhancement, frontend

#26 change theme to trifork palette
  src/components/Header/Header.tsx
  src/theme.tsx
Labels: enhancement

#59 Feature/58 GitHub actions
  .github/workflows/autoformat.yml
  .github/workflows/docker-image.yml
  Dockerfile
  README.md
Labels: Orchestration

#63 Feature/56 docker
  Dockerfile
  src/components/BasePage/BasePage.tsx
Labels: Orchestration
